apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coupons-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/redeem
        pathType: Prefix
        backend:
          service:
            name: redeem-service
            port:
              number: 80
      - path: /api/coupon
        pathType: Prefix
        backend:
          service:
            name: redeem-service
            port:
              number: 80
      - path: /api/campaigns
        pathType: Prefix
        backend:
          service:
            name: campaign-service
            port:
              number: 80
